### ISSUE TITLE
在vuejs里由于动态添加的div没有父级的作用域，会导致自定义的class无效

### ISSUE THREAD

**Issue by kiddkyd2** [pprory/eazyDanmaku#1]
由于一般vuejs组件，都是加了<style scoped>来限制颜色作用域，因此，源码里创建div的时候，如果没有作用域的属性，会无效。
另外，能不能加一个style的属性在send里？因为用户的弹幕可能是各种颜色，无法提前定制好class来匹配。

**Comment by pprory** [comment]
第一点可以考虑再写一个不带scoped的style标签， 加style属性是个不错的主意， 我会在后面的版本里加上。😀
