### ISSUE TITLE
支持横竖屏适配的吗？

### ISSUE THREAD

**Issue by vlay1314** [pprory/eazyDanmaku#3]
在切换横屏和竖屏的时候，出来的还是竖屏的

**Comment by pprory** [comment]
可以发图片看看吗， 理论上移动端也是支持的

**Comment by vlay1314** [comment]
@pprory 我以为是可以自动适配横竖屏的，我使用媒体查询器来做强制横屏了就可以了！不然在移动端是竖屏的时候，div是横屏旋转了，但是弹幕还是竖屏播放的。
`
@media screen and (orientation: landscape) {
            .danmaku-container {
                background-color: transparent !important;
                position: absolute !important;
                top: 0;
                left: 0;
                width: 100%;
                height: 150px;
                overflow: hidden;
                pointer-events: none;
            }
        }

    @media screen and (orientation: portrait) {
            .danmaku-container {
                background-color: transparent !important;
                position: absolute !important;
                height: 150px;
                width: 100vh;
                top: 0;
                left: 100vw;
                overflow: hidden;
                pointer-events: none;
                -webkit-transform: rotate(90deg);
                -moz-transform: rotate(90deg);
                -ms-transform: rotate(90deg);
                transform: rotate(90deg);
                transform-origin: 0% 0%;
            }
        }

        .danmaku-wrapper {
            height: 30px;
            line-height: 30px !important;
        }

        .danmaku-send {
            color: black !important
        }
`

**Comment by pprory** [comment]
可以， 牛的
